package com.boilerplate.app.model.dto.request.feign;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Artajasa QR Refund Request DTO matching QRRefundRQ specification
 */
@Getter
@Setter
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TransactionRefundFeignRequestDto {
    
    @NotNull
    @Valid
    @JsonProperty("QRRefundRQ")
    private QRRefundRQ qrRefundRQ;

    @Getter
    @Setter
    @NoArgsConstructor
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class QRRefundRQ {
        // Numeric 4 bytes - fix Value must be "0200" for request message
        private String msgType;
        
        // Numeric 19 bytes - max Customer PAN
        // For QR MPM = value of "fromAccount" from original QR Payment Credit transaction
        // For QR CPM = value of "trxPAN" from original QR Payment Debit transaction
        private String trxPAN;
        
        // Numeric 6 bytes - fix Transaction Code (refer to Processing Code Table)
        private String trxCode;
        
        // Numeric 12 bytes - fix Transaction Amount (Right Justified, Left Pad with Zeroes, 2 decimal point)
        private String trxAmount;
        
        // Numeric 12 bytes - fix Settlement Amount (Right Justified, Left Pad with Zeroes, 2 decimal point)
        // Use only for QR Crossborder, otherwise set to empty string ""
        private String settlementAmount;
        
        // Numeric 12 bytes - fix Account Holder Amount (Right Justified, Left Pad with Zeroes, 2 decimal point)
        // Use only for QR Crossborder, otherwise set to empty string ""
        private String accHolderAmount;
        
        // Datetime 10 bytes - fix Date and time message initiated in GMT. Format: "MMDDhhmmss"
        private String transmissionDateTime;
        
        // Numeric 8 bytes - fix Settlement conversion rate
        // Use only for QR Crossborder, otherwise set to empty string ""
        private String settlementConversionRate;
        
        // Numeric 8 bytes - fix Account holder conversion rate
        // Use only for QR Crossborder, otherwise set to empty string ""
        private String accHolderConversionRate;
        
        // Numeric 6 bytes - fix Message trace number (unique transaction identifier on GMT date)
        private String msgSTAN;
        
        // Time 6 bytes - fix Local time at point of card acceptor. Format: "hhmmss"
        private String trxTime;
        
        // Date 4 bytes - fix Local month and day at point of card acceptor. Format: "MMDD"
        private String trxDate;
        
        // Date 4 bytes - fix Settlement date. Format: "MMDD"
        private String settlementDate;
        
        // Date 4 bytes - fix Conversion date (month and day conversion rate is effective). Format: "MMDD"
        // Use only for QR Crossborder, otherwise set to empty string ""
        private String conversionDate;
        
        // Date 4 bytes - fix Capture date (month and day transaction was processed). Format: "MMDD"
        private String captureDate;
        
        // Numeric 4 bytes - fix Merchant type classification
        // Value taken from original QR Payment Credit or Debit transaction
        private String merchantType;
        
        // Numeric 3 bytes - fix Point of Service Entry Mode
        // Value taken from original QR Payment Credit or Debit transaction
        private String posEntryMode;
        
        // String 9 bytes - fix Transaction fee amount (Format: x + n8, 2 digit decimal)
        // Value taken from original QR Payment Credit or Debit transaction
        private String trxFeeAmount;
        
        // Numeric 11 bytes - max Acquirer identification number (Acquirer's Central Bank Code)
        // Value taken from original QR Payment Credit or Debit transaction
        private String acquirerID;
        
        // Numeric 11 bytes - max Forwarding institution ID
        // For QR Artajasa Network must be "360001"
        private String forwardingID;
        
        // String 12 bytes - fix Retrieval Reference Number (document reference, unique value generated by acquirer)
        private String retrievalReferenceNumber;
        
        // Approval code from original transaction (if available)
        private String approvalCode;
        
        // String 16 bytes - fix Unique terminal code at card acceptor location
        // Value taken from original QR Payment Credit or Debit transaction
        private String terminalID;
        
        // String 15 bytes - fix Merchant identification code
        // Value taken from original QR Payment Credit or Debit transaction
        private String merchantID;
        
        // String 40 bytes - fix Merchant name or location
        // Value taken from original QR Payment Credit or Debit transaction
        private String merchantNameLocation;
        
        // String 255 bytes - max Additional transaction information in TLV format
        // Contains: Tag PI (Product Indicator), Tag CD (Customer Data), Tag MC (Merchant Criteria)
        // Value taken from original QR Payment Credit or Debit transaction
        private String additionalDataPrivate;
        
        // Numeric 3 bytes - fix Transaction currency code (ISO 4217)
        // Value taken from original QR Payment Credit or Debit transaction
        private String trxCurrencyCode;
        
        // Numeric 3 bytes - fix Settlement currency code (ISO 4217)
        // Use only for QR Crossborder, otherwise set to empty string ""
        // Value taken from original QR Payment Credit or Debit transaction
        private String settlementCurrencyCode;
        
        // Numeric 3 bytes - fix Account holder currency code (ISO 4217)
        // Use only for QR Crossborder, otherwise set to empty string ""
        // Value taken from original QR Payment Credit or Debit transaction
        private String accHolderCurrencyCode;
        
        // Numeric 11 bytes - max Issuer identification number (Issuer ID - 8 digit NNS)
        // Value taken from original QR Payment Credit or Debit transaction
        private String issuerID;
        
        // Numeric 19 bytes - max Customer account identifier
        // For QR MPM: Mandatory - value of DE 2 from original QR Payment Credit transaction
        // For QR CPM: Conditional - must be filled if MPAN available, otherwise set to empty string ""
        private String fromAccount;
        
        // String 20 bytes - fix Invoice number
        // Position 1-10: Invoice Number (current refund invoice)
        // Position 11-20: Original Transaction Invoice Number (last 10 digits of original retrievalReferenceNumber)
        private String invoiceNumber;
    }
}

