-- This file is kept for backward compatibility
-- All sample data including merchant-x is now in 06-insert-all-sample-data.sql
-- This file will be executed before 06-insert-all-sample-data.sql
-- The comprehensive sample data in 06-insert-all-sample-data.sql will override/update these entries
