spring:
  application:
    name: service-gateway

server:
  port: 8999

gateway:
  oauth2:
    validation-endpoint: http://service-authentication/api/oauth/token/validate
  public-paths:
    - /api/oauth/token
    - /actuator
    - /swagger-ui
    - /api-docs
    - /v3/api-docs
  routes:
    - path: /api/oauth/**
      service: service-authentication
      requires-auth: false
    - path: /api/partners/**
      service: service-authentication
      requires-auth: true
    - path: /api/accounts/**
      service: service-account
      requires-auth: true
    - path: /api/payments/**
      service: service-payment
      requires-auth: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,circuitbreakerevents
  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: true
    propagation:
      type: W3C
  otlp:
    tracing:
      endpoint: http://${JAEGER_HOST:localhost}:4318/v1/traces
  metrics:
    tags:
      service: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      serviceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        recordExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

logging:
  level:
    io.github.resilience4j: DEBUG
