spring:
  application:
    name: service-account
  datasource:
    url: jdbc:postgresql://postgresql:5432/app_db
    username: app_user
    password: app_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      otlp:
        enabled: true
    propagation:
      type: W3C
    jdbc:
      enabled: true
  observations:
    key-values:
      enabled: true
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  metrics:
    tags:
      service: ${spring.application.name}